# Gopkg.toml
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#

[[constraint]]
  branch = "master"
  name = "github.com/apcera/termtables"
  source = "github.com/brettski/go-termtables"

[[override]]
 name = "github.com/docker/distribution"
 version = "2.7.0-rc.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "v20.10.6"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/elgs/gojq"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/jsonq"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
 name = "github.com/stretchr/testify"
 version = "1.2.2"

[[constraint]]
 name = "github.com/alecthomas/units"
 branch = "master"

[prune]
  go-tests = true
  unused-packages = true
